// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozgvpetrufggoiuqpruy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96Z3ZwZXRydWZnZ29pdXFwcnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTYyNzgsImV4cCI6MjA2NTQ5MjI3OH0.mNEKpUwvDF8095zHM4ye_UXivnAFbKqWaSBTROUau80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);